---
- name: "Ensure repository alpine /etc/apk/repositories"
  lineinfile:
    path: /etc/apk/repositories
    create: yes
    owner: root
    group: root
    mode: "0644"
    line: "{{ item }}"
    state: present
  loop: "{{ alpine_apk_repositories }}"

- name: "Update repositories"
  command: "{{ update_repositories }}"

- name: "package present"
  package:
    name: "{{ common_packages }}"
    state: present

- name: "Config Daemon Docker"
  command: "{{ item }}"
  loop: "{{ docker_daemon }}"
