---
- hosts: servers
  become: true
  roles:
    - server

- hosts: localhost
  gather_facts: false
  tasks:
    - slurp:
        src: /var/lib/rancher/k3s/server/token
      register: slurped_token
      delegate_to: server

    - set_fact:
        token: "{{ slurped_token.content | b64decode }}"
        server_ip: "{{ hostvars['server'].ansible_host }}"

- hosts: agents
  become: true
  roles:
    - agent
